### ISSUE TITLE
Coverage with Codecov

### ISSUE THREAD

**Issue by RDIL** [zlanguage/zcomp#19]
If you install codecov (https://codecov.io) on the repo, I can set it up in the CI. 

@N8python

**Comment by N8python** [comment]
Sure!

**Comment by N8python** [comment]
I've tried - but I'm not sure how - do you know?

**Comment by RDIL** [comment]
If you switch me to organization owner for a minute I can install it - you can remove extra permissions after

**Comment by N8python** [comment]
Ok. Tell me when ur done.

**Comment by N8python** [comment]
Ok - u have owner access now.
