### ISSUE TITLE
zcomp - command line not found with nvm usage.

### ISSUE THREAD

**Issue by prasad83** [zlanguage/zcomp#617]
```npm install -g @zlanguage/zcomp``` with nvm failed to setup zcomp command on ubuntu.

I had to define alias to make it work.

```
alias zcomp="node /path/to/nvm_which_current/lib/node_modules/@zlanguage/zcomp/src/commands/index.js"
```

To know the path of nvm directory use:
```
nvm which current
```

**Comment by N8python** [comment]
I'm afraid this repo is long past maintaining. I appreciate your interest and I'm happy you found a fix, but the library I used for aliasing/making commands all those years ago... probs very outdated.
